import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`font-lexend bg-[#001946]`}
      >
        <Header />
        {/* Ellipse 8 - Blurred background effect */}
        <div className="absolute w-[639px] h-[639px] bg-[rgba(49,119,255,0.2)] blur-[225px]" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
